---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: home
          value: /tekton
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output

  params:
    - name: repo-url
      type: string
      description: The URL of the git repository to clone
    - name: branch
      type: string
      description: The branch to clone
      default: "main"
    - name: app-name
      type: string
      description: The name of the application
    - name: build-image
      type: string
      description: The image to build and deploy

  tasks:
    # Step 1: Cleanup workspace
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    # Step 2: Git Clone
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: output

      runAfter:
        - cleanup

    # Step 3: Flake8 Linting
    - name: lint
      taskRef:
        name: flake8
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: output

      runAfter:
        - clone

    # Step 4: Nose Tests
    - name: tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

      runAfter:
        - lint

    # Step 5: Buildah Build & Push
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: output

      runAfter:
        - tests

    # Step 6: Deploy to OpenShift
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask

      runAfter:
        - build
